export const list=[
    {
      name:'Home',
      imgsrc:require('./assets/home.png'),
      url:'http://123.207.66.160/#/index'
    },
    {
      name:'Github',
      imgsrc:require('./assets/Github.png'),
      url:'https://github.com/buxiuchen'
    },
    {
      name:'ECUT',
      imgsrc:require('./assets/school.png'),
      url:'http://www.ecut.edu.cn/'
    },
    {
      name:'Management',
      imgsrc:require('./assets/manage.png'),
      url:'http://123.207.66.160/#/manage'
    },
    {
      name:'Note',
      imgsrc:require('./assets/note.png'),
      url:'http://123.207.66.160/#/note'
    }
]